# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-11 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS.Book')),
                ('rollno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS.Student')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='issuebook',
            unique_together=set([('rollno', 'bookid')]),
        ),
    ]
