# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-11 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0002_auto_20180311_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuebook',
            old_name='bookid',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='issuebook',
            old_name='rollno',
            new_name='student',
        ),
        migrations.AlterUniqueTogether(
            name='issuebook',
            unique_together=set([('student', 'book')]),
        ),
    ]
